### ISSUE TITLE
Offer does not contain any datetime field for the start of the offer.

### ISSUE THREAD

**Issue by gitterrost4** [fahrgemeinschaft/share-square-commons#1]
In Branch `develop`: The `Offer` class currently holds no time-information of when the offer will actually take place. This needs to be added.

**Comment by gitterrost4** [comment]
Is there any reason why the start time is split into three fields instead of providing it as an ISO8601 time?

**Comment by kat-ka** [comment]
We have three fields instead of one since only the second one `startTime` is mandatory. If it happens for example every Monday the `startDate` is not necessary needed.

**Comment by gitterrost4** [comment]
Are periodic offers part of the protocol? How would I post an offer that recurs every Monday?

Also, are we sure that all backends don't require a date?

**Comment by kat-ka** [comment]
The advantage of three fields is that we can treat them differently. The ISO standard remains the same. And periodic offers are definitely planed.

**Comment by kat-ka** [comment]
Deployed to Test https://share2hub-r2g-api-dev.apps.prod.rd2g.de
